### ISSUE TITLE
TypeError when creating a new domain

### ISSUE THREAD

**Issue by enortham** [sosedoff/rackspace-clouddns#7]
If you create a new domain you get an error in the response.

```
dns.create_domain('somedomain.com', 'your@email.com')
TypeError: can't convert String into Integer
from /Users/enortham/.rvm/gems/ruby-1.9.3-p194/gems/rackspace-clouddns-0.1.1/lib/clouddns/client/domains.rb:60:in `[]'
    from /Users/enortham/.rvm/gems/ruby-1.9.3-p194/gems/rackspace-clouddns-0.1.1/lib/clouddns/client/domains.rb:60:in `create_domain'
    from (irb):12
    from /Users/enortham/.rvm/rubies/ruby-1.9.3-p194/bin/irb:16:in `<main>'
```

Note that the domain is actually created in Rackspace. I tried this in Ruby 1.8.7 and 1.9.3.

**Comment by sosedoff** [comment]
There might be lots of errors, i havent maintained this library for a long time.
